FROM openjdk:11

RUN apt-get update && apt-get install -y git maven

RUN git clone https://github.com/denza/quarkus.git

WORKDIR quarkus
RUN mvn clean install

CMD java -jar target/quarkus-0.0.1-SNAPSHOT.jar